
# backend
isSvcFrontend: false

name: backend
namespace: helm #backend

cm_name: my-configmap
secret_name: my-secret
serviceName: svc-backend

replicas: 1
image: cisko6/backendubuntu2
tag: latest
port: 9080
targetPort: 9080

mongodb:
  enabled: true
  connectionString: "mongodb://backend-mongodb:27017/platformsdb" # "mongodb://svc-backend:27017/platformsdb"
  auth:
    usernames: ["username"]
    passwords: ["password"]
    databases: ["platformsdb"]
  extraEnvVars:
    - name: MONGO_CONN_STR
      value: "mongodb://backend-mongodb:27017/platformsdb" #"mongodb://username:password@backend-mongodb:27017/platformsdb"
    - name: MONGO_USERNAME
      value: "username"
    - name: MONGO_PASSWORD
      value: "password"

# mongosh -u username -p password "mongodb://backend-mongodb.backend.svc.cluster.local:27017/platformsdb"