
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        ports:
        - containerPort: {{ .Values.targetPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.cm_name }}
          - secretRef:
              name: {{ .Values.secret_name }}
