
# frontend
isSvcFrontend: true

name: frontend
namespace: helm #frontend

cm_name: my-configmap
secret_name: my-secret
serviceName: svc-frontend

react_api: "svc-backend.helm.svc.cluster.local:9080"

replicas: 1
image: cisko6/frontendubuntu2
tag: latest
port: 8080
targetPort: 8080

mongodb:
  enabled: false