
{{- if .Values.isSvcFrontend }} # aby sa nespustal 2x
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cm_name }}
  namespace: {{ .Values.namespace }}
data:
  REACT_APP_APIHOSTPORT: {{ .Values.react_api }}
  MONGO_CONN_STR: "mongodb://backend-mongodb:27017/platformsdb" #"mongodb://svc-backend:27017/platformsdb"
{{- end }}
