apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
{{- if .Values.isSvcFrontend }}
  type: NodePort #LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
{{- if .Values.isSvcFrontend }}
    nodePort: 31111
{{- else }}
    nodePort: 32222
{{- end }}
 #- protocol: TCP mozno toto doplnit idk
  